branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - build-dist (22)
      - test (22)
      - windows
permissionRules:
  - team: compwright
    permission: admin
